import type { Metadata } from "next";
// Импорт шрифтов Google: Geist (основной), Geist Mono (моноширинный), Inter (запасной)
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils"; // утилита для объединения CSS-классов (из shadcn/ui)
import { Header } from "@/components/header/header";
import { Toaster } from "@/components/ui/sonner";

// Настройка шрифта Inter с латиницей и CSS-переменной для глобального использования
const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

// Настройка Geist Sans с CSS-переменной
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Настройка Geist Mono с CSS-переменной
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// SEO/метаданные страницы
export const metadata: Metadata = {
  title: "Собиратель ПК",
  description: "Generated by create next app",
};

// Корневой layout приложения (обертка для всех страниц)
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ru"
      className={cn(
        "h-full", // полная высота
        "antialiased", // сглаживание шрифтов
        geistSans.variable, // CSS-переменная для Geist Sans
        geistMono.variable, // CSS-переменная для Geist Mono
        "font-sans", // базовый шрифт (sans-serif)
        inter.variable, // CSS-переменная для Inter
        "dark" // начальная тема - темная (статически задана)
      )}
    >
      <body className="min-h-full flex flex-col">
        {<Header />}
        {children}
        <Toaster />
      </body>
    </html>
  );
}
